---
  - name: Stop ec2 instances
    hosts: localhost
    gather_facts: false
    vars:
#sesuikan
      instance_ids:
        - 'i-04ef89809322becb9'
        - 'i-01e35874ce7ccc568'
        - 'i-0aa494910fac44f42'
#sesuaikan
        region: ap-southeast-1
    tasks:
      - name: Stop the ec2 instances
        ec2:
          instance_ids: '{{ instance_ids }}'
          region: '{{ region }}'
#terminate = absent
#stop = stopped
#restart = restarted
#start = running
          state: absent
          wait: True
#sesuaikan
          vpc_subnet_id: subnet-e803fa8e
          assign_public_ip: yes